<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecoretoscala"
    nsURI="http://ecore-to-scala.obeonetwork.org" nsPrefix="ecoretoscala">
  <eClassifiers xsi:type="ecore:EClass" name="EmptyClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendingClass" eSuperTypes="#//ExtendedClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendingMultipleClasses" eSuperTypes="#//ExtendedClass #//ExtendingClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractClass" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInterfaceClass" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceTypeNameClass" instanceTypeName="MyClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceTypeQualifiedNameClass" instanceClassName="org.obeonetwork.pim.ecore.gen.scala.model.otherpackage.MyClass"/>
</ecore:EPackage>
